/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FeesManager;


import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;


/**
 *
 * @author niten
 */
public class Print_Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Print_Receipt
     */
    public Print_Receipt() {
        initComponents();
        setIconImage();
        getRecords();
        Container c = getContentPane();
        c.setBackground(new Color(255,204,204));
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

    }
    
     private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/FeesManager/images/fmlogoR.png")));
    }
    
    public void getRecords(){
        try {
         Connection con = DBConnection.getConnection();
         PreparedStatement pst = con.prepareStatement("select * from fees_details order by reciept_no desc fetch first 1 row only");
         ResultSet rs =  pst.executeQuery();
         rs.next();
         txt_receipt_no.setText(rs.getString("reciept_no"));
         txt_PaymentMode.setText(rs.getString("payment_mode"));
         
         String paymentMode = rs.getString("payment_mode");
         
         if (paymentMode.equalsIgnoreCase("cash")){
            lbl_cheque_dd.setText("_");
            txt_cheque_dd.setText("_");
            lbl_bankName.setText("_");
            txt_BankName.setText("_");
         }
         
          if (paymentMode.equalsIgnoreCase("dd")){
            lbl_cheque_dd.setText("DD No : ");
            txt_cheque_dd.setText(rs.getString("dd_no"));
            txt_BankName.setText(rs.getString("bank_name"));
         }
         
          if (paymentMode.equalsIgnoreCase("card")){
            lbl_cheque_dd.setText("-");
            txt_cheque_dd.setText("_");
            txt_BankName.setText(rs.getString("bank_name"));
         }
         

            txt_ReceivedFrom.setText(rs.getString("student_name"));
            txt_date.setText(rs.getString("date"));
            txt_gstin.setText(rs.getString("gstin"));
            txt_year1.setText(rs.getString("year1"));
            txt_year2.setText(rs.getString("year2"));
            txt_rollNo.setText(rs.getString("roll_no"));
            txt_amount.setText(rs.getString("amount"));
            txt_cgst.setText(rs.getString("cgst"));
            txt_sgst.setText(rs.getString("sgst"));
            txt_CourseName.setText(rs.getString("course_name"));
            txt_TotalAmount.setText(rs.getString("total_amount"));
            txt_TotalInWords.setText(rs.getString("total_in_words"));
            txt_remark.setText(rs.getString("remark"));  
           
           
           
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panal_Print = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_receipt_no = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_rollNo = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        txt_BankName = new javax.swing.JLabel();
        txt_ReceivedFrom = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        txt_CourseName = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_PaymentMode = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JLabel();
        txt_TotalInWords = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_sgst = new javax.swing.JLabel();
        txt_TotalAmount = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PanalSideBar = new javax.swing.JPanel();
        PanalHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        PanalLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        PanalSearchRecord = new javax.swing.JPanel();
        btnSearchRecord = new javax.swing.JLabel();
        PanalEditCourses = new javax.swing.JPanel();
        btnEditCourses = new javax.swing.JLabel();
        PanalCourseList = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        PanalViewAllRecords = new javax.swing.JPanel();
        btnViewAllRecords = new javax.swing.JLabel();
        PanalPrint = new javax.swing.JPanel();
        btnPrint = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Print Receipt");
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panal_Print.setBackground(new java.awt.Color(255, 255, 255));
        Panal_Print.setForeground(new java.awt.Color(0, 0, 102));
        Panal_Print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Board of Technical Education`s");
        Panal_Print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 31));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Government Polytechnic College, Jodhpur");
        Panal_Print.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 531, 31));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Residency Rd, near Jodhpur Nagar Nigam, Surya Colony, Jodhpur, Rajasthan ,342001");
        Panal_Print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 91, 661, 20));

        jLabel4.setBackground(new java.awt.Color(153, 255, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeesManager/images/gpclogo.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panal_Print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 120));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        Panal_Print.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 900, 6));

        txt_receipt_no.setForeground(new java.awt.Color(0, 0, 102));
        txt_receipt_no.setText("Receipt NO ");
        Panal_Print.add(txt_receipt_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 121, 24));

        lbl_cheque_dd.setForeground(new java.awt.Color(0, 0, 102));
        lbl_cheque_dd.setText("Cheque_dd");
        Panal_Print.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 94, 24));

        txt_cheque_dd.setForeground(new java.awt.Color(0, 0, 102));
        txt_cheque_dd.setText("Cheque_dd");
        Panal_Print.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 170, 24));

        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Received From : ");
        Panal_Print.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 94, 24));

        lbl_bankName.setForeground(new java.awt.Color(0, 0, 102));
        lbl_bankName.setText("Bank Name : ");
        Panal_Print.add(lbl_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 24));

        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("The following payment in the college office for the year");
        Panal_Print.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 280, 24));

        txt_rollNo.setForeground(new java.awt.Color(0, 0, 102));
        txt_rollNo.setText("Roll No : ");
        Panal_Print.add(txt_rollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 140, 24));

        txt_date.setForeground(new java.awt.Color(0, 0, 102));
        txt_date.setText("Date : ");
        Panal_Print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 130, 24));

        txt_year2.setForeground(new java.awt.Color(0, 0, 102));
        txt_year2.setText("2020");
        Panal_Print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 24));

        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("-");
        Panal_Print.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 10, 20));

        txt_year1.setForeground(new java.awt.Color(0, 0, 102));
        txt_year1.setText("2021");
        Panal_Print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, 24));

        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("Date : ");
        Panal_Print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 59, 24));

        txt_gstin.setForeground(new java.awt.Color(0, 0, 102));
        txt_gstin.setText("GSTIN : ");
        Panal_Print.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 150, 24));

        txt_BankName.setForeground(new java.awt.Color(0, 0, 102));
        txt_BankName.setText("Bank Name : ");
        Panal_Print.add(txt_BankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 160, 24));

        txt_ReceivedFrom.setForeground(new java.awt.Color(0, 0, 102));
        txt_ReceivedFrom.setText("Received From : ");
        Panal_Print.add(txt_ReceivedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 160, 24));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));
        Panal_Print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 780, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 102));
        Panal_Print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 210, 30));

        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Amount(Rs)");
        Panal_Print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, 24));

        txt_CourseName.setForeground(new java.awt.Color(0, 0, 102));
        txt_CourseName.setText("course");
        Panal_Print.add(txt_CourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 310, 24));

        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("Head");
        Panal_Print.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, 24));

        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Payment Mode : ");
        Panal_Print.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 94, 27));

        txt_PaymentMode.setForeground(new java.awt.Color(0, 0, 102));
        txt_PaymentMode.setText("Payment Mode : ");
        Panal_Print.add(txt_PaymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 130, 27));

        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("Sr NO");
        Panal_Print.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 24));

        jLabel29.setForeground(new java.awt.Color(0, 0, 102));
        jLabel29.setText("1");
        Panal_Print.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 30, 24));

        txt_amount.setForeground(new java.awt.Color(0, 0, 102));
        txt_amount.setText("Amount");
        Panal_Print.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 130, 24));

        txt_TotalInWords.setForeground(new java.awt.Color(0, 0, 102));
        txt_TotalInWords.setText("Total in words : ");
        Panal_Print.add(txt_TotalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 400, 24));

        jLabel32.setForeground(new java.awt.Color(0, 0, 102));
        jLabel32.setText("CGST 9%");
        Panal_Print.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 60, 24));

        txt_cgst.setForeground(new java.awt.Color(0, 0, 102));
        txt_cgst.setText("CGST");
        Panal_Print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 120, 24));

        jLabel34.setForeground(new java.awt.Color(0, 0, 102));
        jLabel34.setText("SGST 9%");
        Panal_Print.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 60, 24));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 102));
        Panal_Print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 780, 16));

        txt_sgst.setForeground(new java.awt.Color(0, 0, 102));
        txt_sgst.setText("SGST");
        Panal_Print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 120, 24));

        txt_TotalAmount.setForeground(new java.awt.Color(0, 0, 102));
        txt_TotalAmount.setText("total");
        Panal_Print.add(txt_TotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 130, 24));

        jLabel37.setForeground(new java.awt.Color(0, 0, 102));
        jLabel37.setText("Receiver Signature");
        Panal_Print.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 110, 24));

        jLabel39.setForeground(new java.awt.Color(0, 0, 102));
        jLabel39.setText("Total in words : ");
        Panal_Print.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 90, 24));

        txt_remark.setForeground(new java.awt.Color(0, 0, 102));
        txt_remark.setText("remark");
        Panal_Print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 700, 24));

        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Receipt NO :            GPC -");
        Panal_Print.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, 24));

        jLabel42.setForeground(new java.awt.Color(0, 0, 102));
        jLabel42.setText("Remark : ");
        Panal_Print.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 60, 24));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 102));
        Panal_Print.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 210, 30));

        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("GSTIN : ");
        Panal_Print.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 50, 24));

        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("Roll No : ");
        Panal_Print.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 50, 24));

        getContentPane().add(Panal_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 900, 740));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Print Receipt");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 250, 60));

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Edit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 70, 100, 40));

        PanalSideBar.setBackground(new java.awt.Color(51, 51, 51));
        PanalSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanalHome.setBackground(new java.awt.Color(51, 51, 51));
        PanalHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 255, 153), null));
        PanalHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeesManager/images/home.png"))); // NOI18N
        btnHome.setText(" HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        PanalHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        PanalSideBar.add(PanalHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 330, 70));

        PanalLogout.setBackground(new java.awt.Color(51, 51, 51));
        PanalLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, new java.awt.Color(0, 255, 153), null));
        PanalLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeesManager/images/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        PanalLogout.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        PanalSideBar.add(PanalLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, 330, 70));

        PanalSearchRecord.setBackground(new java.awt.Color(51, 51, 51));
        PanalSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, new java.awt.Color(0, 255, 153), null));
        PanalSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchRecord.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnSearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeesManager/images/search2.png"))); // NOI18N
        btnSearchRecord.setText(" Search Record");
        btnSearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseExited(evt);
            }
        });
        PanalSearchRecord.add(btnSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        PanalSideBar.add(PanalSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 330, 70));

        PanalEditCourses.setBackground(new java.awt.Color(51, 51, 51));
        PanalEditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, new java.awt.Color(0, 255, 153), null));
        PanalEditCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourses.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnEditCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeesManager/images/edit2.png"))); // NOI18N
        btnEditCourses.setText(" Edit Courses");
        btnEditCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseExited(evt);
            }
        });
        PanalEditCourses.add(btnEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        PanalSideBar.add(PanalEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 330, 70));

        PanalCourseList.setBackground(new java.awt.Color(51, 51, 51));
        PanalCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, new java.awt.Color(0, 255, 153), null));
        PanalCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeesManager/images/list.png"))); // NOI18N
        btnCourseList.setText("Course List");
        btnCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseListMouseExited(evt);
            }
        });
        PanalCourseList.add(btnCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 300, 70));

        PanalSideBar.add(PanalCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 330, 70));

        PanalViewAllRecords.setBackground(new java.awt.Color(51, 51, 51));
        PanalViewAllRecords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, new java.awt.Color(0, 255, 153), null));
        PanalViewAllRecords.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecords.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnViewAllRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeesManager/images/view all record.png"))); // NOI18N
        btnViewAllRecords.setText("View All Records");
        btnViewAllRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllRecordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecordsMouseExited(evt);
            }
        });
        PanalViewAllRecords.add(btnViewAllRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        PanalSideBar.add(PanalViewAllRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 330, 70));

        PanalPrint.setBackground(new java.awt.Color(51, 51, 51));
        PanalPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, new java.awt.Color(0, 255, 153), null));
        PanalPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanalPrintMouseEntered(evt);
            }
        });
        PanalPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrint.setFont(new java.awt.Font("Sylfaen", 0, 25)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeesManager/images/printer-.png"))); // NOI18N
        btnPrint.setText(" Print");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrintMouseExited(evt);
            }
        });
        PanalPrint.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 270, 70));

        PanalSideBar.add(PanalPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 330, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeesManager/images/fmlogoR.png"))); // NOI18N
        jLabel6.setText("  Fees Manager");
        PanalSideBar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 330, 100));

        getContentPane().add(PanalSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 880));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 350, 20));

        setSize(new java.awt.Dimension(1555, 913));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseEntered
     Color clr= new Color(0,102,0);
        PanalPrint.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintMouseEntered

    private void btnPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseExited
        Color clr= new Color(51,51,51);
        PanalPrint.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintMouseExited

    private void PanalPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanalPrintMouseEntered
 // TODO add your handling code here:
    }//GEN-LAST:event_PanalPrintMouseEntered

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
       PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
               Panal_Print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     UpdateFeesDetails EditRecipt = new UpdateFeesDetails();
     EditRecipt.setVisible(true);
     this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        home home = new home();
        home.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        Color clr= new Color(0,102,0);
        PanalHome.setBackground(clr);   // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        Color clr= new Color(51,51,51);
        PanalHome.setBackground(clr);  // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        Color clr= new Color(255,0,0);
        PanalLogout.setBackground(clr);  // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited

        Color clr= new Color(51,51,51);
        PanalLogout.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnSearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseClicked
        SearchRecord searchString = new SearchRecord();
        searchString.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRecordMouseClicked

    private void btnSearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseEntered
        Color clr= new Color(0,102,0);
        PanalSearchRecord.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRecordMouseEntered

    private void btnSearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseExited
        Color clr= new Color(51,51,51);
        PanalSearchRecord.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRecordMouseExited

    private void btnEditCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseClicked

        EditCourse EditCourse = new EditCourse();
        EditCourse.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditCoursesMouseClicked

    private void btnEditCoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseEntered
        Color clr= new Color(0,102,0);
        PanalEditCourses.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditCoursesMouseEntered

    private void btnEditCoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseExited
        Color clr= new Color(51,51,51);
        PanalEditCourses.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditCoursesMouseExited

    private void btnCourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseClicked
        View_Course course = new View_Course();
        course.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseListMouseClicked

    private void btnCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseEntered
        Color clr= new Color(0,102,0);
        PanalCourseList.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseListMouseEntered

    private void btnCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseExited
        Color clr= new Color(51,51,51);
        PanalCourseList.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseListMouseExited

    private void btnViewAllRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordsMouseClicked
        ViewRecords viewRecords = new ViewRecords();
        viewRecords.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllRecordsMouseClicked

    private void btnViewAllRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordsMouseEntered
        Color clr= new Color(0,102,0);
        PanalViewAllRecords.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllRecordsMouseEntered

    private void btnViewAllRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordsMouseExited
        Color clr= new Color(51,51,51);
        PanalViewAllRecords.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllRecordsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanalCourseList;
    private javax.swing.JPanel PanalEditCourses;
    private javax.swing.JPanel PanalHome;
    private javax.swing.JPanel PanalLogout;
    private javax.swing.JPanel PanalPrint;
    private javax.swing.JPanel PanalSearchRecord;
    private javax.swing.JPanel PanalSideBar;
    private javax.swing.JPanel PanalViewAllRecords;
    private javax.swing.JPanel Panal_Print;
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnEditCourses;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnPrint;
    private javax.swing.JLabel btnSearchRecord;
    private javax.swing.JLabel btnViewAllRecords;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JLabel txt_BankName;
    private javax.swing.JLabel txt_CourseName;
    private javax.swing.JLabel txt_PaymentMode;
    private javax.swing.JLabel txt_ReceivedFrom;
    private javax.swing.JLabel txt_TotalAmount;
    private javax.swing.JLabel txt_TotalInWords;
    private javax.swing.JLabel txt_amount;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_receipt_no;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_rollNo;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
